spring:
  profiles:
    active: @spring.profiles.active@
  application:
    name: echochamber
  datasource:
    url: jdbc:${profile.datasource.url}
    username: ${profile.datasource.user}
    password: ${profile.datasource.pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: false

server:
  servlet:
    context-path: "/api/${spring.application.name}"


security:
  jwt:
    secret: "super-secret"
    expiresAfterMinutes: 30